server:
  port: 8000

spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:postgresql://localhost/produto_service
    username: postgres
    password: postman
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernet:
      format_sql: true
  flyway:
    locations:
    - classpath:/db_migration
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true 
      
    
